#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fakenews?useSSL=false&serverTimezone=UTC
#    username: root
#    password:
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#
springdoc:
  swagger-ui:
    path: /swagger-ui.html